2020-08-20 14:45:36,274 ERROR: Exception on /search [GET] [in /volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/volumec/python_programe/python-exercise/microblog-bak/app/main/routes.py", line 161, in search
    if total > page * current_app.config['POSTS_PER_PAGE'] else None
TypeError: '>' not supported between instances of 'dict' and 'int'
2020-08-20 14:48:47,951 INFO: Microblog startup [in /volumec/python_programe/python-exercise/microblog-bak/app/__init__.py:77]
2020-08-20 14:48:52,223 ERROR: Exception on /search [GET] [in /volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/volumec/python_programe/python-exercise/microblog-bak/app/main/routes.py", line 164, in search
    if total > page * current_app.config['POSTS_PER_PAGE'] else None
TypeError: '>' not supported between instances of 'dict' and 'int'
2020-08-20 15:05:02,271 INFO: Microblog startup [in /volumec/python_programe/python-exercise/microblog-bak/app/__init__.py:77]
2020-08-20 15:16:01,670 INFO: Microblog startup [in /volumec/python_programe/python-exercise/microblog-bak/app/__init__.py:77]
2020-08-20 15:18:12,884 INFO: Microblog startup [in /volumec/python_programe/python-exercise/microblog-bak/app/__init__.py:77]
2020-08-20 15:21:39,366 INFO: Microblog startup [in /volumec/python_programe/python-exercise/microblog-bak/app/__init__.py:77]
2020-08-20 15:21:44,340 ERROR: Exception on /search [GET] [in /volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/volumec/python_programe/python-exercise/microblog-bak/app/main/routes.py", line 156, in search
    print(len(posts))
TypeError: object of type 'BaseQuery' has no len()
2020-08-20 15:22:10,040 INFO: Microblog startup [in /volumec/python_programe/python-exercise/microblog-bak/app/__init__.py:77]
2020-08-20 15:26:37,000 INFO: Microblog startup [in /volumec/python_programe/python-exercise/microblog-bak/app/__init__.py:77]
2020-08-20 15:32:50,289 INFO: Microblog startup [in /volumec/python_programe/python-exercise/microblog-bak/app/__init__.py:77]
2020-08-20 15:33:58,198 INFO: Microblog startup [in /volumec/python_programe/python-exercise/microblog-bak/app/__init__.py:77]
2020-08-20 15:34:02,180 ERROR: Exception on /index [GET] [in /volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/volumec/python_programe/python-exercise/microblog-bak/app/main/routes.py", line 43, in index
    page, current_app.config['POSTS_PER_PAGE'], False)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 490, in paginate
    if per_page < 0:
TypeError: '<' not supported between instances of 'str' and 'int'
2020-08-20 15:34:03,853 ERROR: Exception on /index [GET] [in /volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/volumec/python_programe/python-exercise/microblog-bak/app/main/routes.py", line 43, in index
    page, current_app.config['POSTS_PER_PAGE'], False)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 490, in paginate
    if per_page < 0:
TypeError: '<' not supported between instances of 'str' and 'int'
