2020-08-20 14:31:06,486 ERROR: Exception on /search [GET] [in /volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/volumec/python_programe/python-exercise/microblog-bak/app/main/routes.py", line 157, in search
    if total > page * current_app.config['POSTS_PER_PAGE'] else None
TypeError: '>' not supported between instances of 'dict' and 'int'
2020-08-20 14:37:12,683 INFO: Microblog startup [in /volumec/python_programe/python-exercise/microblog-bak/app/__init__.py:77]
2020-08-20 14:39:11,071 INFO: Microblog startup [in /volumec/python_programe/python-exercise/microblog-bak/app/__init__.py:77]
2020-08-20 14:39:16,892 ERROR: Exception on /search [GET] [in /volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/volumec/python_programe/python-exercise/microblog-bak/app/main/routes.py", line 157, in search
    if total > page * current_app.config['POSTS_PER_PAGE'] else None
TypeError: '>' not supported between instances of 'dict' and 'int'
2020-08-20 14:39:26,763 INFO: Microblog startup [in /volumec/python_programe/python-exercise/microblog-bak/app/__init__.py:77]
2020-08-20 14:41:37,067 INFO: Microblog startup [in /volumec/python_programe/python-exercise/microblog-bak/app/__init__.py:77]
2020-08-20 14:41:44,882 ERROR: Exception on /search [GET] [in /volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/volumec/python_programe/python-exercise/microblog-bak/app/main/routes.py", line 156, in search
    print("type POSTS_PER_PAG is: "%(type(current_app.config['POSTS_PER_PAGE'])))
TypeError: not all arguments converted during string formatting
2020-08-20 14:42:52,766 INFO: Microblog startup [in /volumec/python_programe/python-exercise/microblog-bak/app/__init__.py:77]
2020-08-20 14:42:59,200 ERROR: Exception on /search [GET] [in /volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/volumec/python_programe/python-exercise/microblog-bak/app/main/routes.py", line 157, in search
    if total > page * current_app.config['POSTS_PER_PAGE'] else None
TypeError: '>' not supported between instances of 'dict' and 'int'
2020-08-20 14:44:33,287 INFO: Microblog startup [in /volumec/python_programe/python-exercise/microblog-bak/app/__init__.py:77]
2020-08-20 14:44:38,833 ERROR: Exception on /search [GET] [in /volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/volumec/python_programe/python-exercise/microblog-bak/venv/lib64/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/volumec/python_programe/python-exercise/microblog-bak/app/main/routes.py", line 159, in search
    if total > page * current_app.config['POSTS_PER_PAGE'] else None
TypeError: '>' not supported between instances of 'dict' and 'int'
2020-08-20 14:45:27,940 INFO: Microblog startup [in /volumec/python_programe/python-exercise/microblog-bak/app/__init__.py:77]
